blank_issues_enabled: true
contact_links:
  - name: Open a blank issue
    url: https://github.com/cncf/tag-contributor-strategy/issues/new
    about: Please open a blank issue to if you don't see your issue type here.
