body:
  - type: markdown
    attributes:
      value: |
        This template has moved to the TOC repo. 
        Please complete the Governance Review Request [here](https://github.com/cncf/toc/issues)