name: Governance review request
description: OLD, Please Open In TOC Repo
title: "Please Do Not Submit Here"
labels: ["wg/governance", "project-governance-review"]
assignees:
  - jberkus
  - geekygirldawn
body:
  - type: markdown
    attributes:
      value: |
        Governance reviews have moved to the [TOC Repository](https://github.com/cncf/toc/issues), please open yours there instead.
